version: "3.8"

services:
  mysql:
    platform: linux/x86_64 # no ARM image available yet
    image: mysql
    restart: always
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: password
