spring:
  datasource:
    url: "jdbc:mysql://${DB_HOST}:${DB_PORT}/db?createDatabaseIfNotExist=true"
    username: root
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: create-drop
    show-sql: true
