name: Build

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Run lint
        run: ./gradlew ktlintCheck

      - name: Build with Gradle
        run: ./gradlew test bootJar --scan --stacktrace

      - uses: actions/upload-artifact@v2
        with:
          name: App
          path: build/libs/App.jar