name: Build

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper

      - name: Build with Gradle
        run: ./gradlew test bootJar --scan --stacktrace

      - name: Create coverage report
        run: ./gradlew koverReport

      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./build/reports/kover/project-xml/report.xml

      - uses: actions/upload-artifact@v2
        with:
          name: App
          path: build/libs/App.jar
